name = "FinancialSymbology"
uuid = "9d391c44-9e33-4973-a6cd-c9dd346bb47a"
authors = ["Rob <robfoxsimms@gmail.com> and contributors"]
version = "0.1.0"

[deps]

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
ProfileView = "c46f51b8-102a-5cf2-8d2c-8597cb0e0da7"

[targets]
test = ["Test"]
